### ISSUE TITLE
"Upload image" button still uses markdown syntax

### ISSUE THREAD

**Issue by leksar** [APXEOLOG/nodebb-plugin-bbcodes#3]
![asasasas](https://leto21d.storage.yandex.net/rdisk/99d7de90c84f5c80ea432ca982c2e455037c04b415bda4a51589e3eb968d9525/inf/hOGBUpvzwdUDEzFeoztMbhL9bnS0qzEd_65SK2Ve9Hb1_k2oNtdgsObbGCEzbfIewtaY2hMaOU9sUyZIcGcUDA==?uid=0&filename=2015-07-10%2009-38-36%20%D0%90%D0%BD%D0%BE%D0%BD%D1%81%D1%8B%20%20%20metagamers.ru%20-%20Google%20Chrome.png&disposition=inline&hash=&limit=0&content_type=image%2Fpng&tknv=v2&rtoken=2eb9375dc1866bae16554c1a724f334e&force_default=no)

**Comment by APXEOLOG** [comment]
Plugin currently don't have button for IMG tag, so i assume you have another plugin installed, wich add this button to the composer
